spring:
  config:
    import:
      additional-location: 'classpath:application-*.yml'

  profiles:
    include:
      - redis
  devtools:
    livereload:
      enabled: true
server:
  port: 8081


logging:
  level:
    root: debug

